config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :products, only: :index

  namespace :admin do
    resources :products
    resources :orders
  end

  post :add_item_to_current_order, to: 'orders#add_item_to_current_order'
  get :get_current_order, to: 'orders#get_current_order'
  get :get_current_order_with_items, to: 'orders#get_current_order_with_items'
  get :cart, to: 'orders#cart'
  post :remove_item_from_cart, to: 'orders#remove_item_from_current_order'
  post :finalise_order, to: 'orders#finalise'
  get :thankyou, to: 'orders#thankyou'
end

app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id             :integer          not null, primary key
#  discount       :decimal(10, 2)   default(0.0)
#  status         :integer          default("pending")
#  subtotal       :decimal(10, 2)   default(0.0)
#  taxes          :decimal(10, 2)   default(0.0)
#  total          :decimal(10, 2)   default(0.0)
#  total_shipping :decimal(10, 2)   default(0.0)
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Order < ApplicationRecord
  has_many :order_items, dependent: :destroy

  enum status: %i[pending complete cancelled refunded]

  before_save :update_subtotal, :update_shipping, :update_discount, :update_total

  def total_quantity
    order_items.pluck(:quantity).sum
  end

  def to_builder
    items = order_items.includes(:product)

    Jbuilder.new do |order|
      order.(self, :id, :subtotal, :total, :total_shipping, :taxes, :discount)
      order.order_items items do |item|
        order.id item.id
        order.product_name item.product.try(:name)
        order.quantity item.quantity
        order.unit_price item.unit_price
        order.total_price item.total_order_item_price
      end
    end
  end

  private

  def update_subtotal
    self.subtotal = order_items.pluck(:total_order_item_price).sum
  end

  def update_shipping
    qty = total_quantity
    standard_shipping_cost = 30
    free_shipping_qty = 10

    if qty > 0 && qty < free_shipping_qty
      self.total_shipping = standard_shipping_cost
    else
      self.total_shipping = 0
    end
  end

  def update_discount
    discount_rate = 0.1
    min_discount_qty = 20
    self.discount = total_quantity > min_discount_qty ? subtotal * discount_rate : 0
  end

  def update_total
    self.total = (subtotal + taxes + total_shipping) - discount
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to admin_order_path(@order), notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to admin_order_path(@order), notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to admin_orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:total, :subtotal, :taxes, :total_shipping, :discount)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def get_current_order
    render json: current_order
  end

  def get_current_order_with_items
    render json: current_order.to_builder.attributes!
  end

  def add_item_to_current_order
    # check if item already exists in order
    existing_item = current_order.order_items.find_by(product_id: params[:order_item][:product_id])

    existing_item.present? ? update_existing_item(existing_item) : add_new_item
  end

  def remove_item_from_current_order
    item = current_order.order_items.find(params[:item_id])
    item.destroy!
    render json: current_order.to_builder.attributes!
  end

  def cart
  end

  def finalise
    current_order.complete!
    redirect_to thankyou_path
  end

  def thankyou
    # save order for displaying any custom thankyou message, and reset
    @completed_order = current_order
    create_new_order
  end

  private

  def order_item_params
    params.require(:order_item).permit(
      :product_id,
      :quantity
    )
  end

  def add_new_item
    @new_order_item = current_order.order_items.build(order_item_params)
    if @new_order_item.save
      render json: current_order
    else
      render :json => { errors: @updated_order.errors.full_messages},
        status: 422
    end
  end

  def update_existing_item(order_item)
    order_item.quantity = order_item.quantity + params[:order_item][:quantity].to_i
    if order_item.save
      render json: current_order
    else
      render :json => { errors: order_item.errors.full_messages}
    end
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/orders/_form.html.erb
<%= form_with(model: [:admin, order], local: true) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :total %>
    <%= form.number_field :total %>
  </div>

  <div class="field">
    <%= form.label :subtotal %>
    <%= form.number_field :subtotal %>
  </div>

  <div class="field">
    <%= form.label :taxes %>
    <%= form.number_field :taxes %>
  </div>

  <div class="field">
    <%= form.label :total_shipping %>
    <%= form.number_field :total_shipping %>
  </div>

  <div class="field">
    <%= form.label :discount %>
    <%= form.number_field :discount %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', admin_order_path(@order) %> |
<%= link_to 'Back', admin_orders_path %>

app/views/admin/orders/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>Orders</h1>

  <table class="table">
    <thead>
      <tr>
        <th>Order ID</th>
        <th>Subtotal</th>
        <th>Taxes</th>
        <th>Total shipping</th>
        <th>Discount</th>
        <th>Total</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @orders.each do |order| %>
        <tr>
          <td><%= order.id %></td>
          <td><%= number_to_currency(order.subtotal) %></td>
          <td><%= number_to_currency(order.taxes) %></td>
          <td><%= number_to_currency(order.total_shipping) %></td>
          <td><%= number_to_currency(order.discount) %></td>
          <td class="font-weight-bold"><%= number_to_currency(order.total) %></td>
          <td><%= link_to 'Show', admin_order_path(order) %></td>
          <td><%= link_to 'Edit', edit_admin_order_path(order) %></td>
          <td><%= link_to 'Destroy', admin_order_path(order), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', admin_orders_path %>

app/views/admin/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Total:</strong>
  <%= @order.total %>
</p>

<p>
  <strong>Subtotal:</strong>
  <%= @order.subtotal %>
</p>

<p>
  <strong>Taxes:</strong>
  <%= @order.taxes %>
</p>

<p>
  <strong>Discount:</strong>
  <%= @order.discount %>
</p>

<p>
  <strong>Total shipping:</strong>
  <%= @order.total_shipping %>
</p>

<%= link_to 'Edit', edit_admin_order_path(@order) %> |
<%= link_to 'Back', admin_orders_path %>