config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :products, only: :index

  namespace :admin do
    resources :products
    resources :orders
  end

  post :add_item_to_current_order, to: 'orders#add_item_to_current_order'
  get :get_current_order, to: 'orders#get_current_order'
  get :get_current_order_with_items, to: 'orders#get_current_order_with_items'
  get :cart, to: 'orders#cart'
  post :remove_item_from_cart, to: 'orders#remove_item_from_current_order'
  post :finalise_order, to: 'orders#finalise'
  get :thankyou, to: 'orders#thankyou'
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id           :integer          not null, primary key
#  description  :text
#  in_stock_qty :integer
#  name         :string
#  price        :decimal(10, 2)
#  sku          :string
#  status       :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Product < ApplicationRecord
  has_one_attached :product_image

  enum status: %i[disabled active]
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to admin_product_path(@product), notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to admin_product_path(@product), notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to admin_products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :price, :sku, :in_stock_qty, :status, :product_image)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.active
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.erb
<%= form_with(model: [:admin, product], local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :sku %>
    <%= form.text_field :sku %>
  </div>

  <div class="field">
    <%= form.label :in_stock_qty %>
    <%= form.number_field :in_stock_qty %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.select :status, Product.statuses.keys.to_a %>
  </div>

  <div class="field">
    <%= form.label :product_image %>

    <% if form.object.product_image.attached? %>
      <div>
        <%= image_tag rails_blob_path(form.object.product_image, disposition: "attachment") %>
      </div>
    <% end %>

    <%= form.file_field :product_image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', admin_product_path(@product) %> |
<%= link_to 'Back', admin_products_path %>

app/views/admin/products/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>Products</h1>

  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Price</th>
        <th>Sku</th>
        <th>In stock qty</th>
        <th>Status</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @products.each do |product| %>
        <tr>
          <td><%= product.name %></td>
          <td><%= product.description %></td>
          <td><%= product.price %></td>
          <td><%= product.sku %></td>
          <td><%= product.in_stock_qty %></td>
          <td><%= product.status %></td>
          <td><%= link_to 'Show', admin_product_path(product) %></td>
          <td><%= link_to 'Edit', edit_admin_product_path(product) %></td>
          <td><%= link_to 'Destroy', admin_product_path(product), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Product', new_admin_product_path %>
</div>

app/views/admin/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', admin_products_path %>

app/views/admin/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Sku:</strong>
  <%= @product.sku %>
</p>

<p>
  <strong>In stock qty:</strong>
  <%= @product.in_stock_qty %>
</p>

<p>
  <strong>Status:</strong>
  <%= @product.status %>
</p>

<%= link_to 'Edit', edit_admin_product_path(@product) %> |
<%= link_to 'Back', admin_products_path %>